
import { BibleBook, PlanDay } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // 구약
  { id: 'gen', name: '창세기', chapters: 50, testament: 'Old' },
  { id: 'exo', name: '출애굽기', chapters: 40, testament: 'Old' },
  { id: 'lev', name: '레위기', chapters: 27, testament: 'Old' },
  { id: 'num', name: '민수기', chapters: 36, testament: 'Old' },
  { id: 'deu', name: '신명기', chapters: 34, testament: 'Old' },
  { id: 'jos', name: '여호수아', chapters: 24, testament: 'Old' },
  { id: 'jud', name: '사사기', chapters: 21, testament: 'Old' },
  { id: 'rut', name: '룻기', chapters: 4, testament: 'Old' },
  { id: '1sa', name: '사무엘상', chapters: 31, testament: 'Old' },
  { id: '2sa', name: '사무엘하', chapters: 24, testament: 'Old' },
  { id: '1ki', name: '열왕기상', chapters: 22, testament: 'Old' },
  { id: '2ki', name: '열왕기하', chapters: 25, testament: 'Old' },
  { id: '1ch', name: '역대상', chapters: 29, testament: 'Old' },
  { id: '2ch', name: '역대하', chapters: 36, testament: 'Old' },
  { id: 'ezr', name: '에스라', chapters: 10, testament: 'Old' },
  { id: 'neh', name: '느헤미야', chapters: 13, testament: 'Old' },
  { id: 'est', name: '에스더', chapters: 10, testament: 'Old' },
  { id: 'job', name: '욥기', chapters: 42, testament: 'Old' },
  { id: 'psa', name: '시편', chapters: 150, testament: 'Old' },
  { id: 'pro', name: '잠언', chapters: 31, testament: 'Old' },
  { id: 'ecc', name: '전도서', chapters: 12, testament: 'Old' },
  { id: 'sng', name: '아가', chapters: 8, testament: 'Old' },
  { id: 'isa', name: '이사야', chapters: 66, testament: 'Old' },
  { id: 'jer', name: '예레미야', chapters: 52, testament: 'Old' },
  { id: 'lam', name: '예레미야애가', chapters: 5, testament: 'Old' },
  { id: 'ezk', name: '에스겔', chapters: 48, testament: 'Old' },
  { id: 'dan', name: '다니엘', chapters: 12, testament: 'Old' },
  { id: 'hos', name: '호세아', chapters: 14, testament: 'Old' },
  { id: 'joe', name: '요엘', chapters: 3, testament: 'Old' },
  { id: 'amo', name: '아모스', chapters: 9, testament: 'Old' },
  { id: 'oba', name: '오바댜', chapters: 1, testament: 'Old' },
  { id: 'jon', name: '요나', chapters: 4, testament: 'Old' },
  { id: 'mic', name: '미가', chapters: 7, testament: 'Old' },
  { id: 'nah', name: '나훔', chapters: 3, testament: 'Old' },
  { id: 'hab', name: '하박국', chapters: 3, testament: 'Old' },
  { id: 'zep', name: '스바냐', chapters: 3, testament: 'Old' },
  { id: 'hag', name: '학개', chapters: 2, testament: 'Old' },
  { id: 'zec', name: '스가랴', chapters: 14, testament: 'Old' },
  { id: 'mal', name: '말라기', chapters: 4, testament: 'Old' },
  // 신약
  { id: 'mat', name: '마태복음', chapters: 28, testament: 'New' },
  { id: 'mrk', name: '마가복음', chapters: 16, testament: 'New' },
  { id: 'luk', name: '누가복음', chapters: 24, testament: 'New' },
  { id: 'jhn', name: '요한복음', chapters: 21, testament: 'New' },
  { id: 'act', name: '사도행전', chapters: 28, testament: 'New' },
  { id: 'rom', name: '로마서', chapters: 16, testament: 'New' },
  { id: '1co', name: '고린도전서', chapters: 16, testament: 'New' },
  { id: '2co', name: '고린도후서', chapters: 13, testament: 'New' },
  { id: 'gal', name: '갈라디아서', chapters: 6, testament: 'New' },
  { id: 'eph', name: '에베소서', chapters: 6, testament: 'New' },
  { id: 'php', name: '빌립보서', chapters: 4, testament: 'New' },
  { id: 'col', name: '골로새서', chapters: 4, testament: 'New' },
  { id: '1th', name: '데살로니가전서', chapters: 5, testament: 'New' },
  { id: '2th', name: '데살로니가후서', chapters: 3, testament: 'New' },
  { id: '1ti', name: '디모데전서', chapters: 6, testament: 'New' },
  { id: '2ti', name: '디모데후서', chapters: 4, testament: 'New' },
  { id: 'tit', name: '디도서', chapters: 3, testament: 'New' },
  { id: 'phm', name: '빌레몬서', chapters: 1, testament: 'New' },
  { id: 'heb', name: '히브리서', chapters: 13, testament: 'New' },
  { id: 'jas', name: '야고보서', chapters: 5, testament: 'New' },
  { id: '1pe', name: '베드로전서', chapters: 5, testament: 'New' },
  { id: '2pe', name: '베드로후서', chapters: 3, testament: 'New' },
  { id: '1jn', name: '요한1서', chapters: 5, testament: 'New' },
  { id: '2jn', name: '요한2서', chapters: 1, testament: 'New' },
  { id: '3jn', name: '요한3서', chapters: 1, testament: 'New' },
  { id: 'jud_nt', name: '유다서', chapters: 1, testament: 'New' },
  { id: 'rev', name: '요한계시록', chapters: 22, testament: 'New' },
];

export const TOTAL_CHAPTERS = BIBLE_BOOKS.reduce((acc, book) => acc + book.chapters, 0);

const r = (start: number, end: number) => Array.from({length: end - start + 1}, (_, i) => i + start);

const v = (day: number) => `https://www.youtube.com/results?search_query=분당우리교회+90일+쉬운통큰통독+Day+${day}`;

export const CHRONOLOGICAL_PLAN: PlanDay[] = [
  { day: 1, title: '창조와 언약의 기초', videoUrl: v(1), readings: [{ bookId: 'gen', bookName: '창세기', chapters: r(1, 15) }] },
  { day: 2, title: '족장들의 믿음', videoUrl: v(2), readings: [{ bookId: 'gen', bookName: '창세기', chapters: r(16, 26) }] },
  { day: 3, title: '야곱의 파란만장한 삶', videoUrl: v(3), readings: [{ bookId: 'gen', bookName: '창세기', chapters: r(27, 37) }] },
  { day: 4, title: '요셉과 하나님의 섭리', videoUrl: v(4), readings: [{ bookId: 'gen', bookName: '창세기', chapters: r(38, 47) }] },
  { day: 5, title: '이스라엘의 입애굽과 출애굽', videoUrl: v(5), readings: [{ bookId: 'gen', bookName: '창세기', chapters: r(48, 50) }, { bookId: 'exo', bookName: '출애굽기', chapters: r(1, 9) }] },
  { day: 6, title: '열 재앙과 유월절', videoUrl: v(6), readings: [{ bookId: 'exo', bookName: '출애굽기', chapters: r(10, 21) }] },
  { day: 7, title: '시내산 언약과 법전', videoUrl: v(7), readings: [{ bookId: 'exo', bookName: '출애굽기', chapters: r(22, 32) }] },
  { day: 8, title: '성막 봉헌과 제사', videoUrl: v(8), readings: [{ bookId: 'exo', bookName: '출애굽기', chapters: r(33, 40) }, { bookId: 'lev', bookName: '레위기', chapters: r(1, 4) }] },
  { day: 9, title: '정결 규례와 법도', videoUrl: v(9), readings: [{ bookId: 'lev', bookName: '레위기', chapters: r(5, 15) }] },
  { day: 10, title: '속죄일과 성결 법전', videoUrl: v(10), readings: [{ bookId: 'lev', bookName: '레위기', chapters: r(16, 25) }] },
  { day: 11, title: '광야의 인구조사', videoUrl: v(11), readings: [{ bookId: 'lev', bookName: '레위기', chapters: r(26, 27) }, { bookId: 'num', bookName: '민수기', chapters: r(1, 6) }] },
  { day: 12, title: '행진 준비와 모세의 기도', videoUrl: v(12), readings: [{ bookId: 'num', bookName: '민수기', chapters: r(7, 15) }, { bookId: 'psa', bookName: '시편', chapters: [90] }] },
  { day: 13, title: '고라의 반역과 가데스', videoUrl: v(13), readings: [{ bookId: 'num', bookName: '민수기', chapters: r(16, 25) }] },
  { day: 14, title: '광야 2세대의 계수', videoUrl: v(14), readings: [{ bookId: 'num', bookName: '민수기', chapters: r(26, 34) }] },
  { day: 15, title: '신명기 고별 설교 (1)', videoUrl: v(15), readings: [{ bookId: 'num', bookName: '민수기', chapters: [35, 36] }, { bookId: 'deu', bookName: '신명기', chapters: r(1, 7) }] },
  { day: 16, title: '신명기 고별 설교 (2)', videoUrl: v(16), readings: [{ bookId: 'deu', bookName: '신명기', chapters: r(8, 20) }] },
  { day: 17, title: '모세의 마지막과 보호', videoUrl: v(17), readings: [{ bookId: 'deu', bookName: '신명기', chapters: r(21, 34) }, { bookId: 'psa', bookName: '시편', chapters: [91] }] },
  { day: 18, title: '가나안 정복의 시작', videoUrl: v(18), readings: [{ bookId: 'jos', bookName: '여호수아', chapters: r(1, 15) }] },
  { day: 19, title: '땅 분배와 사사 시대 서막', videoUrl: v(19), readings: [{ bookId: 'jos', bookName: '여호수아', chapters: r(16, 24) }, { bookId: 'jud', bookName: '사사기', chapters: [1, 2] }] },
  { day: 20, title: '사사들의 통치', videoUrl: v(20), readings: [{ bookId: 'jud', bookName: '사사기', chapters: r(3, 12) }] },
  { day: 21, title: '삼손과 룻의 사랑', videoUrl: v(21), readings: [{ bookId: 'jud', bookName: '사사기', chapters: r(13, 21) }, { bookId: 'rut', bookName: '룻기', chapters: r(1, 4) }] },
  { day: 22, title: '왕정 시대의 서막', videoUrl: v(22), readings: [{ bookId: '1sa', bookName: '사무엘상', chapters: r(1, 14) }] },
  { day: 23, title: '다윗의 고난과 신뢰 (1)', videoUrl: v(23), readings: [{ bookId: '1sa', bookName: '사무엘상', chapters: r(15, 24) }, { bookId: 'psa', bookName: '시편', chapters: [11, 59, 7, 27, 31, 34, 52] }] },
  { day: 24, title: '다윗의 고난과 신뢰 (2)', videoUrl: v(24), readings: [{ bookId: 'psa', bookName: '시편', chapters: [56, 120, 140, 141, 142, 17, 35, 54, 63, 18] }, { bookId: '1sa', bookName: '사무엘상', chapters: r(25, 31) }] },
  { day: 25, title: '다윗 왕조의 확립 (1)', videoUrl: v(25), readings: [{ bookId: 'psa', bookName: '시편', chapters: [121, 123, 124, 125, 128, 129, 130, 6, 8, 9, 10, 14, 16, 19, 21] }, { bookId: '2sa', bookName: '사무엘하', chapters: r(1, 4) }] },
  { day: 26, title: '성가대와 족보', videoUrl: v(26), readings: [{ bookId: 'psa', bookName: '시편', chapters: [43, 44, 45, 49, 84, 85, 87, 73, 77, 78] }, { bookId: '1ch', bookName: '역대상', chapters: r(3, 6) }] },
  { day: 27, title: '예루살렘 정복', videoUrl: v(27), readings: [{ bookId: 'psa', bookName: '시편', chapters: [81, 88, 92, 93, 102, 103, 104] }, { bookId: '1ch', bookName: '역대상', chapters: r(7, 12) }, { bookId: '2sa', bookName: '사무엘하', chapters: [5] }] },
  { day: 28, title: '언약궤 안치', videoUrl: v(28), readings: [{ bookId: 'psa', bookName: '시편', chapters: [133, 106, 107, 1, 2, 15, 22, 23, 24, 47, 68] }, { bookId: '2sa', bookName: '사무엘하', chapters: [6] }, { bookId: '1ch', bookName: '역대상', chapters: r(13, 16) }] },
  { day: 29, title: '다윗 언약과 승전', videoUrl: v(29), readings: [{ bookId: 'psa', bookName: '시편', chapters: [89, 96, 100, 101, 105, 132, 25, 29, 33, 36, 39] }, { bookId: '2sa', bookName: '사무엘하', chapters: r(7, 9) }, { bookId: '1ch', bookName: '역대상', chapters: r(17, 18) }] },
  { day: 30, title: '승리와 참회 (1)', videoUrl: v(30), readings: [{ bookId: 'psa', bookName: '시편', chapters: [50, 53, 60, 75, 20, 65, 66, 67, 69, 70] }, { bookId: '2sa', bookName: '사무엘하', chapters: r(10, 12) }, { bookId: '1ch', bookName: '역대상', chapters: r(19, 20) }] },
  { day: 31, title: '승리와 참회 (2)', videoUrl: v(31), readings: [{ bookId: 'psa', bookName: '시편', chapters: [32, 51, 86, 122, 3, 4, 12, 13, 28, 55] }, { bookId: '2sa', bookName: '사무엘하', chapters: r(13, 18) }] },
  { day: 32, title: '다윗의 말년 고백', videoUrl: v(32), readings: [{ bookId: 'psa', bookName: '시편', chapters: [26, 40, 58, 61, 62, 64, 5, 38, 41, 42, 57] }, { bookId: '2sa', bookName: '사무엘하', chapters: r(19, 23) }] },
  { day: 33, title: '성전 건축 준비 (1)', videoUrl: v(33), readings: [{ bookId: 'psa', bookName: '시편', chapters: [95, 97, 98, 99, 30, 108, 109, 110] }, { bookId: '2sa', bookName: '사무엘하', chapters: [24] }, { bookId: '1ch', bookName: '역대상', chapters: r(21, 25) }] },
  { day: 34, title: '성전 건축 준비 (2)', videoUrl: v(34), readings: [{ bookId: 'psa', bookName: '시편', chapters: [131, 138, 139, 143, 144, 145, 127, 111, 112, 113, 114, 115, 116, 117, 118, 37, 71, 94] }, { bookId: '1ch', bookName: '역대상', chapters: r(26, 29) }, { bookId: '1ki', bookName: '열왕기상', chapters: [1, 2] }] },
  { day: 35, title: '솔로몬의 지혜와 사랑', videoUrl: v(35), readings: [{ bookId: 'psa', bookName: '시편', chapters: [119, 72] }, { bookId: '1ki', bookName: '열왕기상', chapters: [3, 4] }, { bookId: '2ch', bookName: '역대하', chapters: [1] }, { bookId: 'sng', bookName: '아가', chapters: r(1, 8) }] },
  { day: 36, title: '잠언의 지혜 (1)', videoUrl: v(36), readings: [{ bookId: 'pro', bookName: '잠언', chapters: r(1, 15) }] },
  { day: 37, title: '성전 건축의 시작', videoUrl: v(37), readings: [{ bookId: 'pro', bookName: '잠언', chapters: r(16, 24) }, { bookId: '1ki', bookName: '열왕기상', chapters: [5, 6] }, { bookId: '2ch', bookName: '역대하', chapters: [2, 3] }] },
  { day: 38, title: '성전 봉헌과 감사', videoUrl: v(38), readings: [{ bookId: '1ki', bookName: '열왕기상', chapters: [7, 8] }, { bookId: '2ch', bookName: '역대하', chapters: r(4, 7) }, { bookId: 'psa', bookName: '시편', chapters: [136, 134, 146, 147, 148, 149, 150] }] },
  { day: 39, title: '잠언과 전도서 (1)', videoUrl: v(39), readings: [{ bookId: '1ki', bookName: '열왕기상', chapters: [9] }, { bookId: '2ch', bookName: '역대하', chapters: [8] }, { bookId: 'pro', bookName: '잠언', chapters: r(25, 29) }, { bookId: 'ecc', bookName: '전도서', chapters: r(1, 6) }] },
  { day: 40, title: '분열 왕국의 서막', videoUrl: v(40), readings: [{ bookId: 'ecc', bookName: '전도서', chapters: r(7, 12) }, { bookId: '1ki', bookName: '열왕기상', chapters: r(10, 14) }, { bookId: '2ch', bookName: '역대하', chapters: [9] }, { bookId: 'pro', bookName: '잠언', chapters: [30, 31] }] },
  { day: 41, title: '남북 왕조의 갈등', videoUrl: v(41), readings: [{ bookId: '2ch', bookName: '역대하', chapters: r(10, 17) }, { bookId: '1ki', bookName: '열왕기상', chapters: r(15, 19) }] },
  { day: 42, title: '엘리야와 아합', videoUrl: v(42), readings: [{ bookId: '1ki', bookName: '열왕기상', chapters: r(20, 22) }, { bookId: '2ch', bookName: '역대하', chapters: r(18, 23) }, { bookId: 'oba', bookName: '오바댜', chapters: [1] }, { bookId: 'psa', bookName: '시편', chapters: [82, 83] }] },
  { day: 43, title: '엘리사와 예후', videoUrl: v(43), readings: [{ bookId: '2ki', bookName: '열왕기하', chapters: r(1, 13) }, { bookId: '2ch', bookName: '역대하', chapters: [24] }] },
  { day: 44, title: '북이스라엘의 쇠퇴', videoUrl: v(44), readings: [{ bookId: '2ki', bookName: '열왕기하', chapters: r(14, 15) }, { bookId: '2ch', bookName: '역대하', chapters: r(25, 26) }] },
  { day: 45, title: '아모스의 경고', videoUrl: v(45), readings: [{ bookId: 'isa', bookName: '이사야', chapters: r(5, 12) }, { bookId: 'amo', bookName: '아모스', chapters: r(1, 9) }, { bookId: '2ch', bookName: '역대하', chapters: [27] }] },
  { day: 46, title: '앗수르의 위협', videoUrl: v(46), readings: [{ bookId: 'mic', bookName: '미가', chapters: r(1, 7) }, { bookId: '2ch', bookName: '역대하', chapters: [28] }, { bookId: '2ki', bookName: '열왕기하', chapters: r(16, 17) }, { bookId: 'isa', bookName: '이사야', chapters: r(13, 22) }] },
  { day: 47, title: '호세아의 사랑', videoUrl: v(47), readings: [{ bookId: 'isa', bookName: '이사야', chapters: r(23, 27) }, { bookId: '2ki', bookName: '열왕기하', chapters: [18] }, { bookId: '2ch', bookName: '역대하', chapters: r(29, 31) }, { bookId: 'psa', bookName: '시편', chapters: [48] }, { bookId: 'hos', bookName: '호세아', chapters: r(1, 14) }] },
  { day: 48, title: '이사야의 예언 (1)', videoUrl: v(48), readings: [{ bookId: 'isa', bookName: '이사야', chapters: r(28, 39) }, { bookId: 'psa', bookName: '시편', chapters: [76] }] },
  { day: 49, title: '이사야의 예언 (2)', videoUrl: v(49), readings: [{ bookId: 'isa', bookName: '이사야', chapters: r(40, 53) }, { bookId: '2ki', bookName: '열왕기하', chapters: r(18, 19) }, { bookId: 'psa', bookName: '시편', chapters: [46, 80, 135] }] },
  { day: 50, title: '유다의 타락', videoUrl: v(50), readings: [{ bookId: 'isa', bookName: '이사야', chapters: r(54, 66) }, { bookId: '2ki', bookName: '열왕기하', chapters: [20, 21] }] },
  { day: 51, title: '요시야의 종교 개혁', videoUrl: v(51), readings: [{ bookId: '2ch', bookName: '역대하', chapters: r(32, 35) }, { bookId: 'nah', bookName: '나훔', chapters: r(1, 3) }, { bookId: '2ki', bookName: '열왕기하', chapters: r(22, 23) }, { bookId: 'zep', bookName: '스바냐', chapters: r(1, 3) }] },
  { day: 52, title: '예레미야의 소명 (1)', videoUrl: v(52), readings: [{ bookId: 'jer', bookName: '예레미야', chapters: r(1, 17) }] },
  { day: 53, title: '예레미야의 소명 (2)', videoUrl: v(53), readings: [{ bookId: 'jer', bookName: '예레미야', chapters: r(18, 31) }] },
  { day: 54, title: '예루살렘 함락', videoUrl: v(54), readings: [{ bookId: 'jer', bookName: '예레미야', chapters: r(32, 40) }, { bookId: 'psa', bookName: '시편', chapters: [74, 79] }, { bookId: '2ki', bookName: '열왕기하', chapters: r(24, 25) }, { bookId: '2ch', bookName: '역대하', chapters: [36] }] },
  { day: 55, title: '하박국의 질문', videoUrl: v(55), readings: [{ bookId: 'hab', bookName: '하박국', chapters: r(1, 3) }, { bookId: 'jer', bookName: '예레미야', chapters: r(41, 50) }] },
  { day: 56, title: '예레미야 애가와 환상', videoUrl: v(56), readings: [{ bookId: 'jer', bookName: '예레미야', chapters: [51, 52] }, { bookId: 'lam', bookName: '예레미야애가', chapters: r(1, 5) }, { bookId: 'ezk', bookName: '에스겔', chapters: r(1, 4) }] },
  { day: 57, title: '에스겔의 파수꾼 (1)', videoUrl: v(57), readings: [{ bookId: 'ezk', bookName: '에스겔', chapters: r(5, 17) }] },
  { day: 58, title: '에스겔의 파수꾼 (2)', videoUrl: v(58), readings: [{ bookId: 'ezk', bookName: '에스겔', chapters: r(18, 27) }] },
  { day: 59, title: '열국에 대한 심판', videoUrl: v(59), readings: [{ bookId: 'ezk', bookName: '에스겔', chapters: r(28, 39) }] },
  { day: 60, title: '새 성전의 환상', videoUrl: v(60), readings: [{ bookId: 'ezk', bookName: '에스겔', chapters: r(40, 48) }] },
  { day: 61, title: '다니엘의 신앙', videoUrl: v(61), readings: [{ bookId: 'joe', bookName: '요엘', chapters: r(1, 3) }, { bookId: 'dan', bookName: '다니엘', chapters: r(1, 9) }] },
  { day: 62, title: '포로 귀환의 시작', videoUrl: v(62), readings: [{ bookId: 'dan', bookName: '다니엘', chapters: r(10, 12) }, { bookId: 'ezr', bookName: '에스라', chapters: r(1, 6) }, { bookId: 'psa', bookName: '시편', chapters: [137] }, { bookId: 'hag', bookName: '학개', chapters: r(1, 2) }] },
  { day: 63, title: '에스더의 헌신', videoUrl: v(63), readings: [{ bookId: 'zec', bookName: '스가랴', chapters: r(1, 14) }, { bookId: 'est', bookName: '에스더', chapters: r(1, 10) }] },
  { day: 64, title: '에스라와 느헤미야', videoUrl: v(64), readings: [{ bookId: 'ezr', bookName: '에스라', chapters: r(7, 10) }, { bookId: 'neh', bookName: '느헤미야', chapters: r(1, 10) }] },
  { day: 65, title: '성벽 완성과 말라기', videoUrl: v(65), readings: [{ bookId: 'neh', bookName: '느헤미야', chapters: r(11, 13) }, { bookId: 'psa', bookName: '시편', chapters: [126] }, { bookId: 'mal', bookName: '말라기', chapters: r(1, 4) }] },
  { day: 66, title: '예수의 탄생', videoUrl: v(66), readings: [{ bookId: 'luk', bookName: '누가복음', chapters: [1, 2] }, { bookId: 'jhn', bookName: '요한복음', chapters: [1] }, { bookId: 'mat', bookName: '마태복음', chapters: [1] }] },
  { day: 67, title: '세례와 사역의 시작', videoUrl: v(67), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: r(2, 4) }, { bookId: 'luk', bookName: '누가복음', chapters: r(2, 5) }, { bookId: 'mrk', bookName: '마가복음', chapters: [1] }, { bookId: 'jhn', bookName: '요한복음', chapters: r(1, 4) }] },
  { day: 68, title: '하나님 나라의 비유', videoUrl: v(68), readings: [{ bookId: 'mrk', bookName: '마가복음', chapters: [2, 3] }, { bookId: 'jhn', bookName: '요한복음', chapters: [5] }, { bookId: 'luk', bookName: '누가복음', chapters: [6] }] },
  { day: 69, title: '병자를 고치심', videoUrl: v(69), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: [8, 11, 12, 13] }, { bookId: 'luk', bookName: '누가복음', chapters: [7, 8] }] },
  { day: 70, title: '오병이어와 갈릴리 사역', videoUrl: v(70), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: [8, 9, 10, 14] }, { bookId: 'mrk', bookName: '마가복음', chapters: r(4, 6) }, { bookId: 'luk', bookName: '누가복음', chapters: [9] }, { bookId: 'jhn', bookName: '요한복음', chapters: [6] }] },
  { day: 71, title: '제자도와 가르침', videoUrl: v(71), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: r(15, 18) }, { bookId: 'mrk', bookName: '마가복음', chapters: r(7, 9) }, { bookId: 'luk', bookName: '누가복음', chapters: [9] }, { bookId: 'jhn', bookName: '요한복음', chapters: [7, 8] }] },
  { day: 72, title: '선한 목자와 비유', videoUrl: v(72), readings: [{ bookId: 'jhn', bookName: '요한복음', chapters: [9, 10] }, { bookId: 'luk', bookName: '누가복음', chapters: r(10, 15) }] },
  { day: 73, title: '나사로와 예루살렘 입성', videoUrl: v(73), readings: [{ bookId: 'luk', bookName: '누가복음', chapters: r(16, 18) }, { bookId: 'jhn', bookName: '요한복음', chapters: [11] }, { bookId: 'mat', bookName: '마태복음', chapters: r(19, 21) }, { bookId: 'mrk', bookName: '마가복음', chapters: [10] }] },
  { day: 74, title: '종말의 징조와 권위', videoUrl: v(74), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: r(20, 22) }, { bookId: 'luk', bookName: '누가복음', chapters: r(18, 19) }, { bookId: 'mrk', bookName: '마가복음', chapters: r(11, 12) }, { bookId: 'jhn', bookName: '요한복음', chapters: [12] }] },
  { day: 75, title: '최후의 만찬 준비', videoUrl: v(75), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: r(23, 26) }, { bookId: 'luk', bookName: '누가복음', chapters: r(20, 21) }, { bookId: 'mrk', bookName: '마가복음', chapters: r(13, 14) }] },
  { day: 76, title: '고난과 십자가', videoUrl: v(76), readings: [{ bookId: 'luk', bookName: '누가복음', chapters: r(22, 23) }, { bookId: 'jhn', bookName: '요한복음', chapters: r(13, 19) }, { bookId: 'mat', bookName: '마태복음', chapters: [27] }, { bookId: 'mrk', bookName: '마가복음', chapters: [15] }] },
  { day: 77, title: '부활과 성령 강림', videoUrl: v(77), readings: [{ bookId: 'mat', bookName: '마태복음', chapters: [28] }, { bookId: 'mrk', bookName: '마가복음', chapters: [16] }, { bookId: 'luk', bookName: '누가복음', chapters: [24] }, { bookId: 'jhn', bookName: '요한복음', chapters: [20, 21] }, { bookId: 'act', bookName: '사도행전', chapters: r(1, 6) }] },
  { day: 78, title: '초대 교회의 확산', videoUrl: v(78), readings: [{ bookId: 'act', bookName: '사도행전', chapters: r(7, 14) }] },
  { day: 79, title: '이방인 선교의 시작', videoUrl: v(79), readings: [{ bookId: 'jas', bookName: '야고보서', chapters: r(1, 5) }, { bookId: 'act', bookName: '사도행전', chapters: [15, 16] }, { bookId: 'gal', bookName: '갈라디아서', chapters: r(1, 6) }] },
  { day: 80, title: '바울의 전도 여행', videoUrl: v(80), readings: [{ bookId: 'act', bookName: '사도행전', chapters: r(17, 19) }, { bookId: '1co', bookName: '고린도전서', chapters: r(1, 4) }, { bookId: '1th', bookName: '데살로니가전서', chapters: r(1, 5) }, { bookId: '2th', bookName: '데살로니가후서', chapters: r(1, 3) }] },
  { day: 81, title: '교회의 질서와 사랑', videoUrl: v(81), readings: [{ bookId: '1co', bookName: '고린도전서', chapters: r(5, 16) }] },
  { day: 82, title: '사도의 직분과 로마서', videoUrl: v(82), readings: [{ bookId: '2co', bookName: '고린도후서', chapters: r(1, 13) }, { bookId: 'act', bookName: '사도행전', chapters: [20] }, { bookId: 'rom', bookName: '로마서', chapters: r(1, 3) }] },
  { day: 83, title: '믿음으로 말미암는 의', videoUrl: v(83), readings: [{ bookId: 'rom', bookName: '로마서', chapters: r(4, 16) }] },
  { day: 84, title: '옥중 서신 (1)', videoUrl: v(84), readings: [{ bookId: 'act', bookName: '사도행전', chapters: r(20, 28) }, { bookId: 'col', bookName: '골로새서', chapters: r(1, 4) }, { bookId: 'phm', bookName: '빌레몬서', chapters: [1] }] },
  { day: 85, title: '옥중 서신 (2)', videoUrl: v(85), readings: [{ bookId: 'eph', bookName: '에베소서', chapters: r(1, 6) }, { bookId: 'php', bookName: '빌립보서', chapters: r(1, 4) }] },
  { day: 86, title: '목회 서신과 베드로', videoUrl: v(86), readings: [{ bookId: '1ti', bookName: '디모데전서', chapters: r(1, 6) }, { bookId: 'tit', bookName: '디도서', chapters: r(1, 3) }, { bookId: '1pe', bookName: '베드로전서', chapters: r(1, 5) }] },
  { day: 87, title: '더 좋은 언약 히브리서', videoUrl: v(87), readings: [{ bookId: 'heb', bookName: '히브리서', chapters: r(1, 13) }] },
  { day: 88, title: '믿음의 경주', videoUrl: v(88), readings: [{ bookId: '2ti', bookName: '디모데후서', chapters: r(1, 4) }, { bookId: '2pe', bookName: '베드로후서', chapters: r(1, 3) }, { bookId: 'jud_nt', bookName: '유다서', chapters: [1] }] },
  { day: 89, title: '요한의 편지', videoUrl: v(89), readings: [{ bookId: '1jn', bookName: '요한1서', chapters: r(1, 5) }, { bookId: '2jn', bookName: '요한2서', chapters: [1] }, { bookId: '3jn', bookName: '요한3서', chapters: [1] }] },
  { day: 90, title: '영원한 승리 요한계시록', videoUrl: v(90), readings: [{ bookId: 'rev', bookName: '요한계시록', chapters: r(1, 22) }] },
];
